server:
<<<<<<< HEAD
  applicationConnectors:
      - type: http
        port: 8080
  adminConnectors:
      - type: http
        port: 8081

=======
  type: simple
  connector:
    type: http
    port: 8080
    
>>>>>>> 23b085d28e47cb02f9020acd58c74b74bdfb0ea4
logging:
  level: INFO
  appenders:
    - type: console
      #currentLogFilename: /logs/sellme.log
      #archive: true
      #archivedLogFilenamePattern: /logs/sellme-%d.log
 
database:
  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver

  # the username
  user: root

  # the password
  password: root

  # the JDBC URL
  url: jdbc:mysql://localhost:3306/test